### ISSUE TITLE
Questions about alignment

### ISSUE THREAD

**Issue by lilkeker** [HYjhkoh/MGTANet#3]
Hi, MGTANet is an excellent work, but I don't  understand the specific operation of its alignment. As far as I know, NuScenes provides the internal and external parameters of the point cloud (Intrinsic and Extrinsic Parameters), which can be used to align multiple frames The BEV features of the point cloud are aligned (align), but MGTANet predicts the offset and weight of the BEV through a network, why not directly use the internal and external parameters to align(like BEVDet4D) , isn't it better?
![image](https://user-images.githubusercontent.com/81810465/221845057-fad94e1e-3f72-40ce-ac68-57e63a4c1793.png)

**Comment by jhkohpav** [comment]
Hello. In BEVDet4D, they only use internal and external parameters for ego-motion compensation. This method is able to align static objects to their current frame position, but dynamic objects remain misaligned. To tackle this issue, we developed a robust alignment method with deformable convolution under motion guidance, allowing for both static and dynamic objects to be aligned.
