### ISSUE TITLE
About sequence processing

### ISSUE THREAD

**Issue by SteveJMao** [HYjhkoh/MGTANet#9]
Hello，great appreciation to your great work！
I was wondering about the processing pipline about long-term bev aggregation. I noticed that you apply 3 past frames to do long term bev temporal alignment and I wondered how you deal with the first two frames which do not have previous 3 frames. Are you just skip the first two frames or apply different operations?
Looking forward to hearing from you soon!

**Comment by junhyung-SPALab** [comment]
Hello. I'm co-author Junhyung Lee. Sorry for the late reply.
As you mentioned, if you use a total of 3 frames including the target frame(denoted as **_t_**), the learning method for the first and second frame of each scene in nuScenes dataset is as follows.

1. Multi frame composition to train the first frame: {**_t-2_**: the first frame, **_t-1_**: the first frame, **_t_**: the first frame}
2. Multi frame composition to train the second frame: {**_t-2_**: the first frame, **_t-1_**: the first frame, **_t_**: the second frame}

Any additional questions are welcome !!

**Comment by SteveJMao** [comment]
Thank you for your replying！Now I understand it!
